#!/bin/bash

# SWM Project - Quick Reference Card
# This file provides a quick reference for all commands and resources

echo "╔═══════════════════════════════════════════════════════════════════════════╗"
echo "║          SMART WASTE MANAGEMENT SYSTEM (SWM) - QUICK REFERENCE          ║"
echo "╚═══════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 PROJECT LOCATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  /Users/mahesharunaladi/Documents/SWM/SWM"
echo ""

echo "🎯 QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Setup:   ./scripts/setup.sh"
echo "  2. Deploy:  ./scripts/deploy-local.sh"
echo "  3. Health:  ./scripts/health-check.sh"
echo ""

echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  READ FIRST:       INDEX.md                (Start here!)"
echo "  Quick Setup:      QUICKSTART.md           (5 minute setup)"
echo "  Project Info:     README.md               (Overview)"
echo "  API Endpoints:    docs/API.md             (All endpoints)"
echo "  CI/CD Pipeline:   docs/CICD.md            (Deployment guide)"
echo "  Architecture:     docs/ARCHITECTURE.md    (System design)"
echo "  Contributing:     docs/CONTRIBUTING.md    (How to contribute)"
echo "  Project Summary:  PROJECT_SUMMARY.md      (Complete overview)"
echo ""

echo "🚀 SERVICE URLS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Frontend:       http://localhost:3001"
echo "  Backend API:    http://localhost:3000/health"
echo "  ML Service:     http://localhost:5000/health"
echo "  PostgreSQL:     localhost:5432"
echo "  Redis:          localhost:6379"
echo ""

echo "🔧 KEY DIRECTORIES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Backend:        ./backend/              (Express.js API)"
echo "  Frontend:       ./frontend/             (React Dashboard)"
echo "  ML Service:     ./ml-service/           (Python Flask)"
echo "  Kubernetes:     ./k8s/                  (K8s configs)"
echo "  CI/CD:          ./.github/workflows/    (Pipelines)"
echo "  Documentation:  ./docs/                 (All docs)"
echo "  Scripts:        ./scripts/              (Utilities)"
echo ""

echo "🛠️ COMMON COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Setup Environment:          ./scripts/setup.sh"
echo "  Deploy Locally:             ./scripts/deploy-local.sh"
echo "  Check Services Health:      ./scripts/health-check.sh"
echo "  Backup Database:            ./scripts/backup.sh"
echo ""
echo "  Start Services:             docker-compose up -d"
echo "  Stop Services:              docker-compose down"
echo "  View Logs:                  docker-compose logs -f [service]"
echo "  Run Backend Tests:          docker-compose exec backend npm test"
echo "  Run Frontend Tests:         docker-compose exec frontend npm test"
echo "  Run ML Tests:               docker-compose exec ml-service pytest"
echo ""

echo "📊 PROJECT STATISTICS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Files Created:              50+"
echo "  Docker Services:            6"
echo "  CI/CD Workflows:            3"
echo "  API Endpoints:              15+"
echo "  Kubernetes Manifests:       5"
echo "  Documentation Pages:        7"
echo "  Utility Scripts:            5"
echo "  Lines of Code:              5000+"
echo ""

echo "🔐 SECURITY FEATURES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✓ JWT Authentication"
echo "  ✓ CORS Protection"
echo "  ✓ Rate Limiting"
echo "  ✓ SQL Injection Prevention"
echo "  ✓ XSS Protection"
echo "  ✓ Security Scanning (Trivy)"
echo "  ✓ Non-root Containers"
echo "  ✓ Read-only Filesystems"
echo ""

echo "🧪 TESTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Backend Tests:              Jest (50%+ coverage)"
echo "  Frontend Tests:             React Testing Library"
echo "  ML Tests:                   Pytest"
echo "  Integration Tests:          Docker Compose"
echo "  Security Tests:             Trivy"
echo ""

echo "🌐 DEVELOPMENT WORKFLOW"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Create feature branch:      git checkout -b feature/name"
echo "  2. Make changes"
echo "  3. Run tests:                  npm test (backend/frontend)"
echo "  4. Commit changes:             git commit -m 'type: message'"
echo "  5. Push to branch:             git push origin feature/name"
echo "  6. Create PR on GitHub"
echo "  7. CI runs automatically"
echo "  8. Merge to develop (auto-staging deploy)"
echo "  9. Create tag for production:  git tag -a v1.0.0"
echo "  10. Auto-deploy to production"
echo ""

echo "🚀 DEPLOYMENT FLOW"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Development:                Docker Compose"
echo "  Staging:                    AWS ECS (Auto on develop merge)"
echo "  Production:                 AWS ECS (Manual on tag)"
echo "  Kubernetes:                 K8s manifests ready"
echo ""

echo "💡 TECH STACK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Frontend:                   React, Redux, TailwindCSS"
echo "  Backend:                    Node.js, Express, PostgreSQL"
echo "  ML/AI:                      Python, Flask, TensorFlow"
echo "  Cache:                      Redis"
echo "  Reverse Proxy:              Nginx"
echo "  Containerization:           Docker, Docker Compose"
echo "  Orchestration:              Kubernetes"
echo "  CI/CD:                      GitHub Actions"
echo "  Cloud:                      AWS (ECS, RDS, ElastiCache)"
echo ""

echo "📞 SUPPORT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  GitHub Issues:              Report bugs"
echo "  GitHub Discussions:         Ask questions"
echo "  Email:                      support@swm.com"
echo ""

echo "✅ NEXT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Read INDEX.md            (Start here!)"
echo "  2. Run setup.sh             (./scripts/setup.sh)"
echo "  3. Start services           (./scripts/deploy-local.sh)"
echo "  4. Verify health            (./scripts/health-check.sh)"
echo "  5. Access frontend          (http://localhost:3001)"
echo "  6. Read documentation       (docs/ folder)"
echo "  7. Start developing         (Create feature branch)"
echo ""

echo "╔═══════════════════════════════════════════════════════════════════════════╗"
echo "║  Project Status: ✅ READY FOR DEVELOPMENT"
echo "║  Created: March 18, 2024"
echo "║  License: MIT"
echo "╚═══════════════════════════════════════════════════════════════════════════╝"
echo ""
