import React, { useState } from 'react';
import '../styles/Analytics.css';

const Analytics = () => {
  const [timeRange, setTimeRange] = useState('7-day');

  const complianceData = {
    compliant: 782,
    pending: 145,
    noncompliant: 73,
  };

  const totalHouseholds = Object.values(complianceData).reduce((a, b) => a + b, 0);

  const dailyCollections = [
    { day: 'Mon', collections: 145, target: 150 },
    { day: 'Tue', collections: 158, target: 150 },
    { day: 'Wed', collections: 142, target: 150 },
    { day: 'Thu', collections: 168, target: 150 },
    { day: 'Fri', collections: 175, target: 150 },
    { day: 'Sat', collections: 132, target: 150 },
    { day: 'Sun', collections: 98, target: 150 },
  ];

  const truckLeaderboard = [
    { truck: 'TRUCK-001', driver: 'John Doe', collections: 45, efficiency: 96 },
    { truck: 'TRUCK-004', driver: 'Sarah Williams', collections: 42, efficiency: 94 },
    { truck: 'TRUCK-003', driver: 'Mike Johnson', collections: 38, efficiency: 92 },
    { truck: 'TRUCK-002', driver: 'Jane Smith', collections: 35, efficiency: 88 },
  ];

  const generatePDFReport = () => {
    const reportContent = `
==============================================
SMART WASTE MANAGEMENT - COMPLIANCE REPORT
==============================================

Report Date: ${new Date().toLocaleDateString()}
Report Period: ${timeRange}

------ COMPLIANCE SUMMARY ------
Total Households: ${totalHouseholds}
Compliant: ${complianceData.compliant} (${Math.round((complianceData.compliant / totalHouseholds) * 100)}%)
Pending: ${complianceData.pending} (${Math.round((complianceData.pending / totalHouseholds) * 100)}%)
Non-Compliant: ${complianceData.noncompliant} (${Math.round((complianceData.noncompliant / totalHouseholds) * 100)}%)

------ DAILY COLLECTIONS ------
${dailyCollections.map(d => `${d.day}: ${d.collections} collections (Target: ${d.target})`).join('\n')}

------ TRUCK PERFORMANCE ------
${truckLeaderboard.map((t, i) => `${i + 1}. ${t.truck} - ${t.driver}: ${t.collections} collections, ${t.efficiency}% efficiency`).join('\n')}

------ KEY METRICS ------
Collection Rate: ${Math.round((complianceData.compliant / totalHouseholds) * 100)}%
Average Efficiency: ${Math.round(truckLeaderboard.reduce((sum, t) => sum + t.efficiency, 0) / truckLeaderboard.length)}%
Total Collections (7-day): ${dailyCollections.reduce((sum, d) => sum + d.collections, 0)}
Avg Collections/Day: ${Math.round(dailyCollections.reduce((sum, d) => sum + d.collections, 0) / dailyCollections.length)}

Generated by Smart Waste Management System
    `;

    // Create a blob and download
    const element = document.createElement('a');
    const file = new Blob([reportContent], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `SWM-Report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="analytics-page">
      <div className="analytics-header">
        <h1>📊 Analytics & Reports</h1>
        <p>Real-time compliance tracking and performance analytics</p>
      </div>

      {/* Controls */}
      <div className="analytics-controls">
        <div className="time-range-selector">
          <label>Time Range:</label>
          <select value={timeRange} onChange={(e) => setTimeRange(e.target.value)}>
            <option value="today">Today</option>
            <option value="7-day">Last 7 Days</option>
            <option value="30-day">Last 30 Days</option>
            <option value="90-day">Last 90 Days</option>
          </select>
        </div>
        <button className="btn btn-primary" onClick={generatePDFReport}>
          📥 Download Report
        </button>
      </div>

      {/* Key Metrics */}
      <div className="metrics-grid">
        <div className="metric-card">
          <div className="metric-icon">✅</div>
          <h3>Compliance Rate</h3>
          <p className="metric-value">
            {Math.round((complianceData.compliant / totalHouseholds) * 100)}%
          </p>
          <p className="metric-desc">{complianceData.compliant} compliant households</p>
        </div>

        <div className="metric-card">
          <div className="metric-icon">📦</div>
          <h3>Total Collections</h3>
          <p className="metric-value">
            {dailyCollections.reduce((sum, d) => sum + d.collections, 0)}
          </p>
          <p className="metric-desc">
            {Math.round(dailyCollections.reduce((sum, d) => sum + d.collections, 0) / dailyCollections.length)}/day average
          </p>
        </div>

        <div className="metric-card">
          <div className="metric-icon">⚡</div>
          <h3>Avg Efficiency</h3>
          <p className="metric-value">
            {Math.round(
              truckLeaderboard.reduce((sum, t) => sum + t.efficiency, 0) /
                truckLeaderboard.length
            )}%
          </p>
          <p className="metric-desc">Fleet average efficiency</p>
        </div>

        <div className="metric-card">
          <div className="metric-icon">🚚</div>
          <h3>Active Trucks</h3>
          <p className="metric-value">{truckLeaderboard.length}</p>
          <p className="metric-desc">Operating successfully</p>
        </div>
      </div>

      {/* Charts Section */}
      <div className="charts-grid">
        {/* Compliance Pie Chart */}
        <div className="chart-card">
          <h2>Compliance Distribution</h2>
          <div className="pie-chart">
            <div className="pie-circle">
              <svg viewBox="0 0 36 36" className="circular-chart">
                <circle
                  cx="18"
                  cy="18"
                  r="15.915"
                  fill="none"
                  stroke="#10b981"
                  strokeWidth="3"
                  strokeDasharray={`${(complianceData.compliant / totalHouseholds) * 100} 100`}
                  opacity="0.8"
                />
                <circle
                  cx="18"
                  cy="18"
                  r="15.915"
                  fill="none"
                  stroke="#f59e0b"
                  strokeWidth="3"
                  strokeDasharray={`${(complianceData.pending / totalHouseholds) * 100} 100`}
                  strokeDashoffset={`${-(complianceData.compliant / totalHouseholds) * 100}`}
                  opacity="0.8"
                />
                <circle
                  cx="18"
                  cy="18"
                  r="15.915"
                  fill="none"
                  stroke="#ef4444"
                  strokeWidth="3"
                  strokeDasharray={`${(complianceData.noncompliant / totalHouseholds) * 100} 100`}
                  strokeDashoffset={`${-((complianceData.compliant + complianceData.pending) / totalHouseholds) * 100}`}
                  opacity="0.8"
                />
              </svg>
              <div className="pie-label">{totalHouseholds}</div>
            </div>
          </div>
          <div className="chart-legend">
            <div className="legend-item">
              <span className="legend-color" style={{ background: '#10b981' }}></span>
              <span>Compliant: {complianceData.compliant}</span>
            </div>
            <div className="legend-item">
              <span className="legend-color" style={{ background: '#f59e0b' }}></span>
              <span>Pending: {complianceData.pending}</span>
            </div>
            <div className="legend-item">
              <span className="legend-color" style={{ background: '#ef4444' }}></span>
              <span>Non-Compliant: {complianceData.noncompliant}</span>
            </div>
          </div>
        </div>

        {/* Daily Collections Chart */}
        <div className="chart-card">
          <h2>7-Day Collection Trend</h2>
          <div className="bar-chart">
            <div className="chart-bars">
              {dailyCollections.map((day, index) => {
                const maxCollection = Math.max(...dailyCollections.map(d => d.collections));
                return (
                  <div key={index} className="bar-container">
                    <div
                      className="bar"
                      style={{ height: `${(day.collections / maxCollection) * 100}%` }}
                    >
                      <span className="bar-value">{day.collections}</span>
                    </div>
                    <span className="bar-label">{day.day}</span>
                  </div>
                );
              })}
            </div>
            <div className="chart-line" style={{ background: '#10b981', height: '2px', margin: '1rem 0' }}></div>
            <p className="chart-note">Target: 150 collections/day</p>
          </div>
        </div>
      </div>

      {/* Truck Leaderboard */}
      <div className="leaderboard-card">
        <h2>🏆 Truck Performance Leaderboard</h2>
        <div className="leaderboard-table">
          <div className="leaderboard-header">
            <span className="rank">Rank</span>
            <span className="truck-info">Truck & Driver</span>
            <span className="collections">Collections</span>
            <span className="efficiency">Efficiency</span>
          </div>
          {truckLeaderboard.map((item, index) => (
            <div key={index} className="leaderboard-row">
              <span className="rank">
                <span className="medal">
                  {index === 0 ? '🥇' : index === 1 ? '🥈' : index === 2 ? '🥉' : ''}
                </span>
                {index + 1}
              </span>
              <span className="truck-info">
                <div>
                  <p className="truck-name">{item.truck}</p>
                  <p className="driver-name">{item.driver}</p>
                </div>
              </span>
              <span className="collections">{item.collections}</span>
              <span className="efficiency">
                <div className="efficiency-display">
                  <div className="eff-bar">
                    <div
                      className="eff-fill"
                      style={{ width: `${item.efficiency}%` }}
                    ></div>
                  </div>
                  <span>{item.efficiency}%</span>
                </div>
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Summary Box */}
      <div className="summary-box">
        <h3>📈 Key Insights</h3>
        <ul>
          <li>✅ Compliance rate improved by 8% compared to last week</li>
          <li>📦 Total collections this period: {dailyCollections.reduce((sum, d) => sum + d.collections, 0)}</li>
          <li>⚡ Fleet average efficiency: {Math.round(truckLeaderboard.reduce((sum, t) => sum + t.efficiency, 0) / truckLeaderboard.length)}%</li>
          <li>🚚 Best performing truck: {truckLeaderboard[0].truck} ({truckLeaderboard[0].driver})</li>
          <li>🎯 {complianceData.pending} households pending verification</li>
        </ul>
      </div>
    </div>
  );
};

export default Analytics;
